name: ✨ Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Feature requests should focus on *value*, not implementation details.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I want…
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you’d like to see happen.
      placeholder: High-level behavior, not code.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you’ve considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, examples, links, or references.
